version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=backend
      - OTEL_LOG_LEVEL=ERROR
    command: ["node", "server.js"]
    depends_on:
      - redis
      - jaeger
  worker:
    build: ./backend
    container_name: worker
    command: ["node", "worker.js"]
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=worker
      - OTEL_LOG_LEVEL=ERROR
    depends_on:
      - redis
      - jaeger
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    restart: always
    ports:
      - "3000"
      - "3333:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
  otel:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.86.0
    command: ["--config=/etc/otelcol-contrib/config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    environment:
      - JAEGER_ENDPOINT=jaeger:4317
      - TEMPO_OTLP_ENDPOINT=${TEMPO_OTLP_ENDPOINT}
      # - TEMPO_CLOUD_USERNAME=${TEMPO_CLOUD_USERNAME}
      # - TEMPO_CLOUD_PASSWORD=${TEMPO_CLOUD_PASSWORD}
      - TEMPO_CLOUD_BASIC_AUTH=${TEMPO_CLOUD_BASIC_AUTH}
      - TEMPO_CLOUD_OTLP_ENDPOINT=${TEMPO_CLOUD_OTLP_ENDPOINT}
    depends_on:
      - jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.47
    ports:
      - 16686:16686 # Jaeger UI
      - "4317" # OTLP gRPC default port
      - 14268:14268
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:80
  grafana_tempo:
    container_name: grafana_tempo
    image: grafana/tempo:latest
    command: ["-config.expand-env=true","-config.file=/etc/tempo.yaml"]
    volumes:
      - ./grafana-tempo/tempo.yml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
      #   - "14268:14268" # jaeger ingest
      #   - "9095:9095" # tempo grpc
      #   - "4318:4318" # otlp http
      #   - "9411:9411" # zipkin
volumes:
  grafana_data:
  tempo_data: