receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
  otlp/jaeger:
    endpoint: "${env:JAEGER_ENDPOINT}"
    tls:
      insecure: true
  otlp/tempo:
    endpoint: "${env:TEMPO_OTLP_ENDPOINT}"
    tls:
      insecure: true
    
processors:
  batch:
    
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/jaeger, otlp/tempo]
