receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
  otlp/jaeger:
    endpoint: "${env:JAEGER_ENDPOINT}"
    tls:
      insecure: true
  otlp/tempo:
    endpoint: "${env:TEMPO_OTLP_ENDPOINT}"
    tls:
      insecure: true
  otlp/tempo_cloud:
    endpoint: "${env:TEMPO_CLOUD_OTLP_ENDPOINT}"
    headers:
      authorization: Basic ${env:TEMPO_CLOUD_BASIC_AUTH}
processors:
  batch:
    
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/jaeger, otlp/tempo, otlp/tempo_cloud]
